# Generated by Django 3.2.12 on 2022-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentface',
            name='studentid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userface',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
