# Generated by Django 3.2.12 on 2022-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220511_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='metadata',
            field=models.CharField(max_length=150),
        ),
    ]
