# Generated by Django 3.2.12 on 2022-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_userphotos_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='metadata',
            field=models.TextField(),
        ),
    ]
